variables_to_describe = [
    "x_yrseduc",
    "x_exp",
    "x_sex",
    "x_married",
    "x_white",
    "x_black",
    "x_asian",
    "wage",
    "y_risk_rateh_occind_ave",
    "y_public",
]

variable_names = {
    "x_yrseduc": "Years of schooling",
    "x_exp": "Years of experience",
    "x_ethn": "Ethnicity",
    "x_sex": "Female",
    "x_union": "Union",
    "x_lma": "Local labor market",
    "x_region": "Region",
    "x_married": "Married",
    "x_white": "White",
    "x_black": "Black",
    "x_asian": "Asian",
    "wage": "Wage (hourly)",
    "y_risk_rateh_occind_ave": "Risk (per 100,000) ",
    "y_public": "Public",
    "y_hospital": "Hospital",
}

covariate_names = [
    "Risk",
    "Public",
    "Public x Years of schooling",
    "Years of schooling",
    "Years of experience",
    "Female",
    "Married",
    "White",
    "Black",
    "Asian",
    "Years of experience (squared)",
    "Risk x Years of schooling",
    "Risk x Years of experience",
    "Risk x Females",
    "Public x Years of schooling",
    "Public x Years of experience",
    "Public x Females",
]

dupuy_galichon_estimates = [
    -0.023,
    -0.062,
    0.081,
    0.057,
    0.084,
    -0.404,
    0.050,
    0.046,
    -0.108,
    -0.069,
    -0.051,
    -0.059,
    0.074,
    -2.388,
    0.838,
    0.096,
    0.548,
    2.981,
    0.046,
    2.233,
]
